### ISSUE TITLE
KeyError: 'cpuprio'

### ISSUE THREAD

**Issue by Sn0ff** [wociscz/lxd-telegraf-stats#2]
Hi I try to run scriptn lxd-telegraf-stats.py  and i get an error

File "/usr/local/sbin/lxd-telegraf-stats.py", line 299, in <module>
    output.append(header + ",metric=status running=" + str(metric['running']) + ",processes=" + str(metric['processes']) + ",cpuprio=" + str(metric['cpuprio']) + ",hddprio=" + str(metric['hddprio']))
KeyError: 'cpuprio'

please help find the problem

Thanks

**Comment by wociscz** [comment]
Hi, which version of lxd are running? 
I've tried `3.17` (snap version) on ubuntu `18.04` and it works as expected without errors.
Looks like sometime there are missing cgroup values for `blkio.weight` and/or `cpu.shares`

I'll push workaround for that.
